services:
  db:
    image: mysql:8.0.30-debian
    ports:
      - 3306:3306
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}

  microservices-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkout-nest-app
    ports:
      - '3001:3001'
    depends_on:
      - db
    volumes:
      - ./src:/app/src
